<template>
  <div class="loader-icon-overlay">
    <div class="icon-content">
      <div></div>
      <div></div>
      <div></div>
    </div>

    <template v-if="showProgress">
      <div class="progress">
        <div :style="{width: `${progressPercentage}%`}"></div>
      </div>

      <h4>{{ progressPercentage }}%</h4>
    </template>
  </div>
</template>
<style scoped>
@keyframes icon-content-o {
  0% {
    opacity: 1;
    transform: translate(0, 0)
  }
  49.99% {
    opacity: 1;
    transform: translate(24px, 0)
  }
  50% {
    opacity: 0;
    transform: translate(24px, 0)
  }
  100% {
    opacity: 0;
    transform: translate(0, 0)
  }
}

@keyframes icon-content {
  0% {
    transform: translate(0, 0)
  }
  50% {
    transform: translate(24px, 0)
  }
  100% {
    transform: translate(0, 0)
  }
}

.icon-content div {
  position: absolute;
  width: 24px;
  height: 24px;
  border-radius: 50%;
}

.icon-content div:nth-child(1) {
  background: #f2121b;
  animation: icon-content 1s linear infinite;
  animation-delay: -0.5s;
}

.icon-content div:nth-child(2) {
  background: #ffffff;
  animation: icon-content 1s linear infinite;
  animation-delay: 0s;
}

.icon-content div:nth-child(3) {
  background: #f2121b;
  animation: icon-content-o 1s linear infinite;
  animation-delay: -0.5s;
}

.loader-icon-overlay {
  overflow: hidden;
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 1rem;
}

.icon-content {
  width: 48px;
  height: 24px;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.icon-content div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */

.progress {
  width: 100%;
  max-width: 280px;
  height: 16px;
  box-shadow: 0 0 0 2px var(--color-akcent-inside);
  border-radius: 8px;
  background-color: var(--color-background);
  border: 3px solid transparent;
  padding: 0;
  overflow: hidden;

  > div {
    background-color: var(--color-akcent);
    height: 10px;
  }
}
</style>
<script setup>
const props = defineProps({
  showProgress: {
    type: Boolean,
    default: false
  },
  progressPercentage: {
    type: Number,
    default: 0
  }
});
</script>
