<template>
  <div class="loader-icon-overlay">
    <div class="icon-content">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style scoped>
@keyframes icon-content-o {
  0% {
    opacity: 1;
    transform: translate(0, 0)
  }
  49.99% {
    opacity: 1;
    transform: translate(24px, 0)
  }
  50% {
    opacity: 0;
    transform: translate(24px, 0)
  }
  100% {
    opacity: 0;
    transform: translate(0, 0)
  }
}

@keyframes icon-content {
  0% {
    transform: translate(0, 0)
  }
  50% {
    transform: translate(24px, 0)
  }
  100% {
    transform: translate(0, 0)
  }
}

.icon-content div {
  position: absolute;
  width: 24px;
  height: 24px;
  border-radius: 50%;
}

.icon-content div:nth-child(1) {
  background: #f2121b;
  animation: icon-content 1s linear infinite;
  animation-delay: -0.5s;
}

.icon-content div:nth-child(2) {
  background: #ffffff;
  animation: icon-content 1s linear infinite;
  animation-delay: 0s;
}

.icon-content div:nth-child(3) {
  background: #f2121b;
  animation: icon-content-o 1s linear infinite;
  animation-delay: -0.5s;
}

.loader-icon-overlay {
  overflow: hidden;
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
}

.icon-content {
  width: 48px;
  height: 24px;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.icon-content div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>
<script setup>
</script>
